# Generated by Django 3.2.7 on 2021-10-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_tehtava_muistiinpano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tehtava',
            name='muistiinpano',
            field=models.TextField(max_length=20000),
        ),
    ]
