# Generated by Django 3.2.7 on 2021-10-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_tehtava_muistiinpano'),
    ]

    operations = [
        migrations.AddField(
            model_name='tehtava',
            name='tehty',
            field=models.BooleanField(default=False),
        ),
    ]
