# Generated by Django 3.2.7 on 2021-10-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_tehtava_tehty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tehtava',
            name='muistiinpano',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
    ]
